### ISSUE TITLE
cergyk - Incorrect bitmask used in _swap will lead to ids in agents mapping to be corrupted

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-looksrare-judging#27]
cergyk

high

# Incorrect bitmask used in _swap will lead to ids in agents mapping to be corrupted
## Summary
Infiltration smart contract uses a common pattern when handling deletion in arrays:
Say we want to delete element i in array of length N:

1/ We swap element at index i with element at index N-1
2/ We update the length of the array to be N-1

Infiltration uses `_swap()` method to do this with a twist:
It updates the status of the removed agent to `Killed`, and initializes id of last agent if it is uninitialized. 

There is a mistake in a bitmask value used for resetting the id of the last agent, which will mess up the game state.

Lines of interest for reference:
https://github.com/sherlock-audit/2023-10-looksrare/blob/main/contracts-infiltration/contracts/Infiltration.sol#L1582-L1592

## Vulnerability Detail

Let's take a look at the custom `assembly` block used to assign an id to the newly allocated `lastAgent`:

```solidity
assembly {
    let lastAgentCurrentValue := sload(lastAgentSlot)
    // Replace the last agent's ID with the current agent's ID.
--> lastAgentCurrentValue := and(lastAgentCurrentValue, not(AGENT__STATUS_OFFSET))
    lastAgentCurrentValue := or(lastAgentCurrentValue, lastAgentId)
    sstore(currentAgentSlot, lastAgentCurrentValue)

    let lastAgentNewValue := agentId
    lastAgentNewValue := or(lastAgentNewValue, shl(AGENT__STATUS_OFFSET, newStatus))
    sstore(lastAgentSlot, lastAgentNewValue)
}
```

The emphasized line shows that `not(AGENT__STATUS_OFFSET)` is used as a bitmask to set the `agentId` value to zero.
However `AGENT__STATUS_OFFSET == 16`, and this means that instead of setting the low-end 2 bytes to zero, this will the single low-end fifth bit to zero. Since bitwise or is later used to assign lastAgentId, if the id in lastAgentCurrentValue is not zero, and is different from lastAgentId, the resulting value is arbitrary, and can cause the agent to be unrecoverable. 

The desired value for the mask is `not(TWO_BYTES_BITMASK)`:

```solidity
    not(AGENT__STATUS_OFFSET) == 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffef
    not(TWO_BYTES_BITMASK)    == 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000
```

## Impact
The ids of the agents will be mixed, this could mean that some agents will be unrecoverable, or duplicated.
Since the attribution of the grand prize relies on the `agentId` stored, we may consider that the legitimate winner can lose access to the prize.

## Tool used

Manual Review

## Recommendation
```diff
assembly {
    let lastAgentCurrentValue := sload(lastAgentSlot)
    // Replace the last agent's ID with the current agent's ID.
-   lastAgentCurrentValue := and(lastAgentCurrentValue, not(AGENT__STATUS_OFFSET))
+   lastAgentCurrentValue := and(lastAgentCurrentValue, not(TWO_BYTES_BITMASK))
    lastAgentCurrentValue := or(lastAgentCurrentValue, lastAgentId)
    sstore(currentAgentSlot, lastAgentCurrentValue)

    let lastAgentNewValue := agentId
    lastAgentNewValue := or(lastAgentNewValue, shl(AGENT__STATUS_OFFSET, newStatus))
    sstore(lastAgentSlot, lastAgentNewValue)
}
```

**Comment by mstpr** [comment]
Escalate

This issue is invalid. Agent ID is either 0 or already set a value. If the agent ID is 0 the OR here does the correct thing by setting the ID of the uninitialized agent. If the agent ID is already set then the or here does not have any impact. 

Only use case
1- Say the agent ID in storage is 0 and we need to set it to 200 

0 OR 200 = 200

Unnecessary assembly operation
2- Say the agent ID in storage is 60 and we need to set it to 60 
60 or 60 = 60

this is unnecessary because `lastAgentId` is always equal to the last 16 bits of the agent ID. Doing an OR operation is unnecessary for the agent that already has initialized ID. As stated above, it only useful when the agentId is 0. 

Regarding to this part:
`lastAgentCurrentValue := and(lastAgentCurrentValue, not(AGENT__STATUS_OFFSET))`
this part is completely unnecessary because we are 100% sure that the lastAgents status is indeed ACTIVE which is 00000000 

you can comment this line in the code and run tests, nothing will change.

**Comment by 0xhiroshi** [comment]
https://github.com/LooksRare/contracts-infiltration/pull/175

**Comment by nevillehuang** [comment]
Agree with escalation, seems like impact is low. Any thoughts @0xhiroshi?

**Comment by 0xhiroshi** [comment]
> Agree with escalation, seems like issue is invalid. Any thoughts @0xhiroshi given u implemented a fix?

It is still an issue, but the severity should be lowered as it only wastes gas instead of breaking the game

**Comment by nevillehuang** [comment]
Agreed, suggestion to make this issue invalid since gas findings are not accepted based on sherlock rules.

**Comment by Evert0x** [comment]
Will accept escalation and make invalid as submitter agreed to low/invalid in DMs.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- Expected issue to be **closed**. Actual issue is **open**.
- [mstpr's escalation](https://github.com/sherlock-audit/2023-10-looksrare-judging/issues/27/#issuecomment-1805667615) could not be resolved, because it has 0 or more than 1 judge reactions.

**Comment by SergeKireev** [comment]
Fix LGTM
