### ISSUE TITLE
AlexCzm - Precision loss in `healProbability` due to rounding error

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-looksrare-judging#32]
AlexCzm

medium

# Precision loss in `healProbability` due to rounding error
## Summary
`healProbability` is subject to slightly precision loss due to rounding error.

## Vulnerability Detail
`healProbability` is used to determine the probability of a wounded agent to be healed. Function output is compared with a Chainlink VRF number. If heal probability is smaller or equal than VRF number agent is healed and killed otherwise. 
As we can see the heal probability is an important aspect of the game dictating whether or not an agent remains in the game. 

In current implementation heal probability is calculated as following:
```js
healProb = (ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD * 99 - 80) * PROBABILITY_PRECISION / 
                       ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE - 
                       (blocksDelay * 19 * PROBABILITY_PRECISION  /
                       ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE
```
Adding the numbers for a better visualization: 
```js
 healProb = (48 * 99 - 80) * 100_000_000 / 47 - 
                       blocksDelay * 19 * 100_000_000 / 47
```
This formula is composed of two main parts that are subtracted from each other. Both parts are divided by the same number, which is 47 (judging from mainnet deployment script values and docs provided). Even if a `PROBABILITY_PRECISION` was used to avoid or minimize the precision loss  it is not enough. 
Instead of subtracting two fractions with same divisor (47)  we subtract the two terms first  and divide the result by `47`  leads to slightly different results in 3 out of 48 `blocksDelay` values:

Add the following code in `Infiltration#healProbability.t.sol` file and execute it with `forge test --mt test_healProbability_RoundingError -vvv`

```solidity
    uint256 private constant PROBABILITY_PRECISION = 100_000_000;
    uint256 private constant ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE = 47;
    function getHealProbabilityWithNoPrecisionLoss(uint256 blocksDelay) pure private returns(uint256 y) {
        y = ((ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD * 99 - 80) * PROBABILITY_PRECISION - 
                blocksDelay * 19 * PROBABILITY_PRECISION
            ) / 
                ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE;
    }
    function test_healProbability_CheckRoundingError() public {
        assertEq(infiltration.healProbability(1), getHealProbabilityWithNoPrecisionLoss(1));
        assertEq(infiltration.healProbability(2), getHealProbabilityWithNoPrecisionLoss(2));
        assertEq(infiltration.healProbability(3), getHealProbabilityWithNoPrecisionLoss(3));
        assertEq(infiltration.healProbability(4), getHealProbabilityWithNoPrecisionLoss(4));
        assertEq(infiltration.healProbability(5), getHealProbabilityWithNoPrecisionLoss(5));
        assertEq(infiltration.healProbability(6), getHealProbabilityWithNoPrecisionLoss(6));
        assertEq(infiltration.healProbability(7), getHealProbabilityWithNoPrecisionLoss(7));
        assertEq(infiltration.healProbability(8), getHealProbabilityWithNoPrecisionLoss(8));
        assertEq(infiltration.healProbability(9), getHealProbabilityWithNoPrecisionLoss(9));
        assertEq(infiltration.healProbability(10), getHealProbabilityWithNoPrecisionLoss(10));
        assertEq(infiltration.healProbability(11), getHealProbabilityWithNoPrecisionLoss(11));
        assertEq(infiltration.healProbability(12), getHealProbabilityWithNoPrecisionLoss(12));
        assertEq(infiltration.healProbability(13), getHealProbabilityWithNoPrecisionLoss(13));
        assertEq(infiltration.healProbability(14), getHealProbabilityWithNoPrecisionLoss(14));
        assertEq(infiltration.healProbability(15), getHealProbabilityWithNoPrecisionLoss(15));
        assertEq(infiltration.healProbability(16), getHealProbabilityWithNoPrecisionLoss(16));
        assertEq(infiltration.healProbability(17), getHealProbabilityWithNoPrecisionLoss(17));
        assertEq(infiltration.healProbability(18), getHealProbabilityWithNoPrecisionLoss(18));
        assertEq(infiltration.healProbability(19), getHealProbabilityWithNoPrecisionLoss(19));
        assertEq(infiltration.healProbability(20), getHealProbabilityWithNoPrecisionLoss(20));
        assertEq(infiltration.healProbability(21), getHealProbabilityWithNoPrecisionLoss(21));
        assertEq(infiltration.healProbability(22), getHealProbabilityWithNoPrecisionLoss(22));
        assertEq(infiltration.healProbability(23), getHealProbabilityWithNoPrecisionLoss(23));
        assertEq(infiltration.healProbability(24), getHealProbabilityWithNoPrecisionLoss(24));
        assertEq(infiltration.healProbability(25), getHealProbabilityWithNoPrecisionLoss(25));
        assertEq(infiltration.healProbability(26), getHealProbabilityWithNoPrecisionLoss(26));
        assertEq(infiltration.healProbability(27), getHealProbabilityWithNoPrecisionLoss(27));
        assertEq(infiltration.healProbability(28), getHealProbabilityWithNoPrecisionLoss(28));
        assertEq(infiltration.healProbability(29), getHealProbabilityWithNoPrecisionLoss(29));
        assertEq(infiltration.healProbability(30), getHealProbabilityWithNoPrecisionLoss(30));
        assertEq(infiltration.healProbability(31), getHealProbabilityWithNoPrecisionLoss(31));
        assertEq(infiltration.healProbability(32), getHealProbabilityWithNoPrecisionLoss(32));
        assertEq(infiltration.healProbability(33), getHealProbabilityWithNoPrecisionLoss(33));
        assertEq(infiltration.healProbability(34), getHealProbabilityWithNoPrecisionLoss(34));
        assertEq(infiltration.healProbability(35), getHealProbabilityWithNoPrecisionLoss(35));
        assertEq(infiltration.healProbability(36), getHealProbabilityWithNoPrecisionLoss(36));
        assertEq(infiltration.healProbability(37), getHealProbabilityWithNoPrecisionLoss(37));
        assertEq(infiltration.healProbability(38), getHealProbabilityWithNoPrecisionLoss(38));
        assertEq(infiltration.healProbability(39), getHealProbabilityWithNoPrecisionLoss(39));
        assertEq(infiltration.healProbability(40), getHealProbabilityWithNoPrecisionLoss(40));
        assertEq(infiltration.healProbability(41), getHealProbabilityWithNoPrecisionLoss(41));
        assertEq(infiltration.healProbability(42), getHealProbabilityWithNoPrecisionLoss(42));
        assertEq(infiltration.healProbability(43), getHealProbabilityWithNoPrecisionLoss(43));
        assertEq(infiltration.healProbability(44), getHealProbabilityWithNoPrecisionLoss(44));
        assertEq(infiltration.healProbability(45), getHealProbabilityWithNoPrecisionLoss(45));
        assertEq(infiltration.healProbability(46), getHealProbabilityWithNoPrecisionLoss(46));
        assertEq(infiltration.healProbability(47), getHealProbabilityWithNoPrecisionLoss(47));
        assertEq(infiltration.healProbability(48), getHealProbabilityWithNoPrecisionLoss(48));
    }
```
Below are only the rounding error cases:
```js
    ├─ [971] Infiltration::healProbability(12) [staticcall]
    │   └─ ← 9455319149 [9.455e9]
    ├─ emit log(: Error: a == b not satisfied [uint])
    ├─ emit log_named_uint(key:       Left, val: 9455319149 [9.455e9])
    ├─ emit log_named_uint(key:      Right, val: 9455319148 [9.455e9])
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001) 
    │   └─ ← ()
...

    ├─ [971] Infiltration::healProbability(24) [staticcall]
    │   └─ ← 8970212766 [8.97e9]
    ├─ emit log(: Error: a == b not satisfied [uint])
    ├─ emit log_named_uint(key:       Left, val: 8970212766 [8.97e9])
    ├─ emit log_named_uint(key:      Right, val: 8970212765 [8.97e9])
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001) 
    │   └─ ← ()

...

    ├─ [971] Infiltration::healProbability(36) [staticcall]
    │   └─ ← 8485106383 [8.485e9]
    ├─ emit log(: Error: a == b not satisfied [uint])
    ├─ emit log_named_uint(key:       Left, val: 8485106383 [8.485e9])
    ├─ emit log_named_uint(key:      Right, val: 8485106382 [8.485e9])
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001) 
    │   └─ ← ()
```
## Impact
The game's outcome might sometimes be incorrect.

## Code Snippet

https://github.com/sherlock-audit/2023-10-looksrare/blob/86e8a3a6d7880af0dc2ca03bf3eb31bc0a10a552/contracts-infiltration/contracts/Infiltration.sol#L379-L381

```solidity
        HEAL_PROBABILITY_MINUEND =
            ((ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD * 99 - 80) * PROBABILITY_PRECISION) /
            ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE;
```

https://github.com/sherlock-audit/2023-10-looksrare/blob/86e8a3a6d7880af0dc2ca03bf3eb31bc0a10a552/contracts-infiltration/contracts/Infiltration.sol#L1019-L1028

```solidity
    function healProbability(uint256 healingBlocksDelay) public view returns (uint256 y) {
        if (healingBlocksDelay == 0 || healingBlocksDelay > ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD) {
            revert InvalidHealingBlocksDelay();
        }


        y =
            HEAL_PROBABILITY_MINUEND -
            ((healingBlocksDelay * 19) * PROBABILITY_PRECISION) /
            ROUNDS_TO_BE_WOUNDED_BEFORE_DEAD_MINUS_ONE;
    }
```

## Tool used

Manual Review, Foundry

## Recommendation
Update the `healProbability` to subtract the two parts first  and divide the result by `47`  in the end.

**Comment by AlexCZM** [comment]
Escalate

While it might seem that the rounding error is insignificant due to their small magnitude, I would like to emphasize that even the smallest error can have a substantial impact on the game’s outcome.
This is not a typical rounding error that affects the reward amount (eg. with a few wei). Instead this rounding error can make difference between a dead agent and an active one and can lead to a different winning agent. 

 In essence, the precision of this calculation directly affects the fairness and integrity of the game.
 
From the Sherlock docs `Criteria for Issue Severity:`
`**Medium:** There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.`
 Given the Sherlock's rules I believe this finding fits the Medium severity criteria.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> While it might seem that the rounding error is insignificant due to their small magnitude, I would like to emphasize that even the smallest error can have a substantial impact on the game’s outcome.
> This is not a typical rounding error that affects the reward amount (eg. with a few wei). Instead this rounding error can make difference between a dead agent and an active one and can lead to a different winning agent. 
> 
>  In essence, the precision of this calculation directly affects the fairness and integrity of the game.
>  
> From the Sherlock docs `Criteria for Issue Severity:`
> `**Medium:** There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.`
>  Given the Sherlock's rules I believe this finding fits the Medium severity criteria. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
> Escalate
> 
> While it might seem that the rounding error is insignificant due to their small magnitude, I would like to emphasize that even the smallest error can have a substantial impact on the game’s outcome. This is not a typical rounding error that affects the reward amount (eg. with a few wei). Instead this rounding error can make difference between a dead agent and an active one and can lead to a different winning agent.
> 
> In essence, the precision of this calculation directly affects the fairness and integrity of the game.
> 
> From the Sherlock docs `Criteria for Issue Severity:` `**Medium:** There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.` Given the Sherlock's rules I believe this finding fits the Medium severity criteria.

I see what you are saying now. Am borderline between low/medium severity considering it requires this line [here](https://github.com/sherlock-audit/2023-10-looksrare/blob/86e8a3a6d7880af0dc2ca03bf3eb31bc0a10a552/contracts-infiltration/contracts/Infiltration.sol#L1358) to be affected, which is dependent on very specific `randomWord % 10_000_000_000`, which I am not sure if its possible. Happy to hear your thoughts @0xhiroshi @nasri136

**Comment by 0xhiroshi** [comment]
> > Escalate
> > While it might seem that the rounding error is insignificant due to their small magnitude, I would like to emphasize that even the smallest error can have a substantial impact on the game’s outcome. This is not a typical rounding error that affects the reward amount (eg. with a few wei). Instead this rounding error can make difference between a dead agent and an active one and can lead to a different winning agent.
> > In essence, the precision of this calculation directly affects the fairness and integrity of the game.
> > From the Sherlock docs `Criteria for Issue Severity:` `**Medium:** There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost.` Given the Sherlock's rules I believe this finding fits the Medium severity criteria.
> 
> I see what you are saying now. Am borderline between low/medium severity considering it requires this line [here](https://github.com/sherlock-audit/2023-10-looksrare/blob/86e8a3a6d7880af0dc2ca03bf3eb31bc0a10a552/contracts-infiltration/contracts/Infiltration.sol#L1358) to be affected, which is dependent on very specific `randomWord % 10_000_000_000`, which I am not sure if its possible. Happy to hear your thoughts @0xhiroshi @nasri136

I think it is a low severity issue. I cannot see how this actually will affect the game's outcome in a practical sense. The probabilities are scaled, to use the contestant's example, we are talking about the difference between 94.55319149% and 94.55319148%.

I can fix it, but I don't think this is a medium severity issue.

**Comment by nevillehuang** [comment]
Agree with sponsor, but ultimately will leave it up to @nasri136 @Evert0x to decide.

**Comment by nasri136** [comment]
Agree with sponsor even if there is a small difference on the % of chance an agent will be heal or not, all agents have the same % with this small difference so there is no impact on the fairness of the game for me

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is

**Comment by Czar102** [comment]
I think it makes sense to allow an imprecision of `1 / PROBABILITY_PRECISION`. I also see this as a low severity issue because those calculations are imprecise by design.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AlexCZM](https://github.com/sherlock-audit/2023-10-looksrare-judging/issues/32/#issuecomment-1804686563): rejected
