### ISSUE TITLE
enfrasico - maximumAmountMintedPerAddress can be bypassed by anyone

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-looksrare-judging#76]
enfrasico

medium

# maximumAmountMintedPerAddress can be bypassed by anyone
## Summary
`maximumAmountMintedPerAddress` being bypassed by the owner is an acceptable risk as documented. However, it can actually be bypassed by anyone.

## Vulnerability Detail
Each address can only mint up to `maximumAmountMintedPerAddress`. However, users can use `transferFrom` from another address to transfer to itself, hence allowing a single address to go over the mint limit even if it is not the owner. `transferFrom` does not check that the `to` address is below the `maximumAmountMintedPerAddress`.

## Impact
Any users can bypass `maximumAmountMintedPerAddress`, even if it is not the owner.

## Code Snippet
https://github.com/sherlock-audit/2023-10-looksrare/blob/main/contracts-infiltration/contracts/Infiltration.sol#L924-L930

## Tool used

Manual Review

## Recommendation
In `transferFrom`, check that `to` address is below the limit after the transfer.

Duplicate of #24

**Comment by Coareal** [comment]
Escalate

I believe that in the accepted risk, `maximumAmountMintedPerAddress can be bypassed` is referring to how the contract owner can bypass it using `premint()`

But this is different from issue #24 as I have explicitly mentioned. We are bypassing it by using `transferFrom`, meaning that ANYONE can bypass it, not just the owner. Only #128 is a duplicated of this.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe that in the accepted risk, `maximumAmountMintedPerAddress can be bypassed` is referring to how the contract owner can bypass it using `premint()`
> 
> But this is different from issue #24 as I have explicitly mentioned. We are bypassing it by using `transferFrom`, meaning that ANYONE can bypass it, not just the owner. Only #128 is a duplicated of this.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nasri136** [comment]
Hello, I am the head of judging for this contest.
Sponsor confirmed me it was an accepted risk
